### ISSUE TITLE
Does not work under Windows 10 Pro?

### ISSUE THREAD

**Issue by eumel1968** [yossTheDev/karbonized#2]
First the most important things:

My operating system: Windows 10 Pro 22H2 Build: 19045.4529 Windows Feature Expirence Pack: 1000.19058.1000.0

I use the Node Version Manager from: https://github.com/coreybutler/nvm-windows

In case I need a different node.js version. So far I have only installed one version. This has worked without any problems for everything I have used node.js for.

node -v
v20.11.1

npm -v
10.4.0

vite -v
vite/5.3.1 win32-x64 node-v20.11.1

I followed the instructions at: https://github.com/yossTheDev/karbonized

	- Run as Web App:
		To start a development server run the following command: yarn dev  (from an admin cmd)

My result:

```
yarn dev
yarn run v1.22.21
$ vite
failed to load config from E:\karbonized\vite.config.ts
error when starting dev server:
Error: Cannot find module 'vite'
Require stack:
- E:\karbonized\vite.config.ts
- C:\Users\USERNAME\AppData\Roaming\nvm\v20.11.1\node_modules\vite\dist\node\chunks\dep-BcXSligG.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1144:15)
    at Module._load (node:internal/modules/cjs/loader:985:27)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (E:\karbonized\vite.config.ts:36:19)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at _require.extensions.<computed> [as .js] (file:///C:/Users/USERNAME/AppData/Roaming/nvm/v20.11.1/node_modules/vite/dist/node/chunks/dep-BcXSligG.js:66925:16)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
error Command failed with exit code 1.
```

Then i deleted the E:\karbonized folder.

After that i installed the karbonized_1.12.0.exe from: https://github.com/yossTheDev/karbonized/releases/tag/v1.12.0

I started the installed software.

The only thing I got to see was a neutral grey screen. Nothing else.

What have I done wrong?

**Comment by yossdotpro** [comment]
Hello, sorry that version has that error in Windows and I haven't had time to update, I recommend that you use the online version

https://karbonized.onrender.com

**Comment by eumel1968** [comment]
Thank you for your feedback.

If an update for the Windows version is released, can you let me know?

Until then I will use the online version.
